PS1='\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\] \[\033[01;32m\]\$\[\033[00m\] '
alias ls='ls --color=auto'
alias l='ls -C'
alias la='l -A'
alias ll='ls -l --group-directories-first'
alias lla='ll -A'
alias dir='l -a'
alias vdir='dir -l'
alias md='mkdir'
alias ren='mv'
alias del='rm'
alias deltree='rm -rf'
alias cls='clear'
alias path='echo $PATH'
alias ver='lsb_release -idrc'
